language: python
os: linux
dist: focal
install:
  - travis_retry pip install -U tox-travis
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py36
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=flake8
script: tox
