arch:
  - amd64
  - ppc64le
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
 - pip install .
 - pip install flake8

script:
 - py.test
 - flake8 . --ignore=E501,E722,E741,W605 --exclude=docs/conf.py
